// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdmxyyo5_7zkvoUfri1zVUqy5k60WHHvI',
    appId: '1:334764737334:web:e547d819a4698281896997',
    messagingSenderId: '334764737334',
    projectId: 'fir-firestore-366cb',
    authDomain: 'fir-firestore-366cb.firebaseapp.com',
    storageBucket: 'fir-firestore-366cb.appspot.com',
    measurementId: 'G-R7XN9QYJ19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuS0x_7sy2DZWTbrWNYyjo1DVUnAng7H0',
    appId: '1:334764737334:android:2edf01b1b3034258896997',
    messagingSenderId: '334764737334',
    projectId: 'fir-firestore-366cb',
    storageBucket: 'fir-firestore-366cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRVTrG0z7yC2mDSTrOiZ6eCr-twSnznOE',
    appId: '1:334764737334:ios:d012eae479da992e896997',
    messagingSenderId: '334764737334',
    projectId: 'fir-firestore-366cb',
    storageBucket: 'fir-firestore-366cb.appspot.com',
    iosBundleId: 'com.becoder.firebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRVTrG0z7yC2mDSTrOiZ6eCr-twSnznOE',
    appId: '1:334764737334:ios:d012eae479da992e896997',
    messagingSenderId: '334764737334',
    projectId: 'fir-firestore-366cb',
    storageBucket: 'fir-firestore-366cb.appspot.com',
    iosBundleId: 'com.becoder.firebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdmxyyo5_7zkvoUfri1zVUqy5k60WHHvI',
    appId: '1:334764737334:web:833abb518aee20ca896997',
    messagingSenderId: '334764737334',
    projectId: 'fir-firestore-366cb',
    authDomain: 'fir-firestore-366cb.firebaseapp.com',
    storageBucket: 'fir-firestore-366cb.appspot.com',
    measurementId: 'G-PNVVSKHJYQ',
  );
}